# Generated by Django 4.2 on 2023-04-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('CP', models.IntegerField()),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('comunidad_autonoma', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono_adicional', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('sitio_web', models.CharField(blank=True, max_length=300, null=True)),
                ('actividad', models.CharField(blank=True, max_length=300, null=True)),
                ('sub_sector', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('nro_empleados', models.IntegerField()),
            ],
        ),
    ]
