# Generated by Django 4.2 on 2023-04-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='booksy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='capital',
            field=models.CharField(blank=True, choices=[(0, '0€ - 3.500€'), (1, '3.500€ - 10.000€'), (2, '10.000€ - 50.000€'), (3, '50.000€ - 100.000€'), (4, 'mayor a 100.000€')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, choices=[(0, 'RECHAZADO'), (1, 'PENDIENTE'), (2, 'NEGOCIACIONES'), (3, 'ACEPTADO')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='facturacion',
            field=models.CharField(blank=True, choices=[(0, '0€ - 500.000€'), (1, '500.000€ - 1.000.000€'), (2, '1.000.000€ - 2.500.000€'), (3, 'mayor a 2.500.000€')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='forma_social',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instagram',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='twitter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='youtube',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nro_empleados',
            field=models.CharField(blank=True, choices=[(0, '0-10'), (1, '10-50'), (2, '50-200'), (3, '200+')], max_length=60, null=True),
        ),
    ]
