# Generated by Django 4.2 on 2023-04-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0002_empresa_booksy_empresa_capital_empresa_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, choices=[('R', 'RECHAZADO'), ('P', 'PENDIENTE'), ('I', 'NEGOCIACIONES'), ('A', 'ACEPTADO')], max_length=2, null=True),
        ),
    ]
