# Generated by Django 4.2 on 2023-05-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0003_alter_empresa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
